
name: bi-hourly sync
on:
  push:
  schedule:
    - cron: 0,30 * * * *

jobs:
  sync_solutions:
    name: Sync Solutions
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: ./update.sh 
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Sync solutions
